TaskSystem/TaskSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from authapp import views as authapp




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authapp.login, name="login"),
    path('main', mainapp.main, name ='main'),
    path('test_main', mainapp.test_main, name='test_main'),
    path('all_users', mainapp.all_users, name="all_users"),
    path('all_users/edit_user/<int:user_id>/', mainapp.edit_user, name='edit_user'),
    path('create', mainapp.create_task, name='create'),
    path("auth/", include('authapp.urls', namespace="auth")),
    path('task_<int:pk>/', mainapp.task, name='task'),
    path('tasks/', include('mytasks.urls', namespace='tasks')),
    path('creation_tasks/', mainapp.creation_tasks, name="creation_tasks"),
    path('creation_tasks/edit/<int:pk>', mainapp.edit_creation_tasks, name="edit_creation_tasks"),
    path('creation_tasks/delete/<int:pk>', mainapp.creation_tasks_delete, name='creation_tasks_delete'),
    path('edit_directory/', include('edit_directory.urls', namespace='edit_directory')),
    path('delete/<int:user_id>', mainapp.delete_user, name='delete_user'),
    path('update_task_status/', mainapp.update_task_status, name='update_task_status'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TaskSystem/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = "authapp"

urlpatterns = [

    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('account/', authapp.account, name ='account'),
    path('create_user/', authapp.create_user, name="create_user")
]

TaskSystem/edit_directory/urls.py
from django.urls import path
import edit_directory.views as edit_directory


app_name = "edit_directory"

urlpatterns = [

    path("", edit_directory.view, name='directory_view'),
    path("create_status", edit_directory.create_status, name='create_status'),
    path("edit_status/<int:status_id>", edit_directory.edit_status, name='edit_status'),
    path('delete_status/<int:pk>', edit_directory.delete_status, name="delete_status"),
    path("create_tasktype", edit_directory.create_tasktype, name='create_tasktype'),
    path('edit_tasktype/<int:tasktype_id>', edit_directory.edit_tasktype, name='edit_tasktype'),
    path('delete_tasktype/<int:pk>', edit_directory.delete_tasktype, name="delete_tasktype"),
]

TaskSystem/mytasks/urls.py
from django.urls import path
import mytasks.views as mytasks


app_name = "mytasks"

urlpatterns = [

    path('', mytasks.view, name='task_view'),
    path('add/<int:task_id>', mytasks.add, name='add'),
    path('delete/<int:mytask_id>', mytasks.delete, name='delete'),
    path('complete/<int:mytask_id>', mytasks.complete, name='complete')


]

TaskSystem/mainapp/models.py
from django.db import models
from authapp.models import CustomUser
from django.utils import timezone
from django.contrib.auth import get_user_model
from edit_directory.models import TaskType, Status

class Task(models.Model):

    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", default=get_user_model(), related_name='authors', blank=True)
    executor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Исполнитель", default=None, related_name='executors', blank=True, null=True)
    title = models.CharField("Заголовок", max_length=100, default=None)
    description = models.TextField("Описание", max_length=250, default="")
    files = models.FileField(upload_to="files/", verbose_name="Файлы", blank=True, default=None)
    tasktype = models.ForeignKey(TaskType, on_delete=models.DO_NOTHING, verbose_name="Тип заявки", default=None)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING, verbose_name="Статус", default="В ожидании")
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.description


class HistoryTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.DO_NOTHING, verbose_name="Задача", default=None, related_name='task')
    #Придумать реализацию сохранения старой инфы
    #Отображение новой инфы
    change = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, verbose_name="Задача", default=None, related_name='сomments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", default=None)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name="Текст", max_length=100, blank=True)
    files = models.FileField(upload_to="comment_files/", verbose_name="Прикрепленные файлы", blank=True, default=None)

    def __str__(self):
        return f"{self.author}: {self.text}"

TaskSystem/mainapp/forms.py
from dataclasses import fields
from django import forms

from authapp.models import Right

from .models import Task, Comment


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("author", "executor", "title", "description", "files", "tasktype", "status",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "author":
                field.widget = forms.HiddenInput()



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text", "files")
                    

class RightForm(forms.ModelForm):
    class Meta:
        model = Right
        fields = ('user_id', 'usertype_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "user_id":
                field.widget = forms.HiddenInput()

TaskSystem/mainapp/views.py
from cmath import pi
from turtle import right
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from .models import Task, Comment
from edit_directory.models import Status
from .forms import RightForm, TaskForm, CommentForm
from authapp.models import CustomUser, UserData, Right
from authapp.forms import CustomUserChangeForm, UserDataForm
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import pickle
# Create your views here.


@login_required
def main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@login_required
def test_main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/test_main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@csrf_exempt
def update_task_status(request):
    if request.method == 'POST':
        # Получаем данные из POST-запроса
        task_id = request.POST.get('task_id')
        status_id = request.POST.get('status_id')
        # Изменяем статус задачи
        task = Task.objects.get(id=task_id)
        status = Status.objects.get(id=status_id)
        task.status = status
        task.save()
        # Возвращаем успешный ответ в формате JSON
        return JsonResponse({'success': True})
    # В случае неправильного метода запроса возвращаем ошибку
    return JsonResponse({'success': False, 'message': 'Метод запроса должен быть POST'})


@login_required
def task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    comment = Comment.objects.filter(task=task)
    form = CommentForm()
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    if request.method =="POST":
        form = CommentForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.data = now
            form.author = request.user
            form.task = task
            form.save()
            return HttpResponseRedirect(reverse('task', args=[pk]))
    return render(request, 'mainapp/task.html', context={
        "title": f"Задача №{task.id}",
        'task':task,
        'comments':comment,
        'form':form,
        "right":right
    })

@login_required
def create_task(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(pk=request.user.pk)
    form = TaskForm()
    # form.author = user
    if request.method == "POST":
        form = TaskForm(data=request.POST)
        
        if form.is_valid():
            form = form.save(commit=False)
            form.author = user
            form.save()
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'mainapp/create.html', context={
        'title':"Создать задачу",
        'form': form,
        "right":right,
    })

@login_required
def creation_tasks(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=Task.objects.filter(author=request.user)
    return render(request, 'mainapp/creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'tasks':task
    })

@login_required
def edit_creation_tasks(request, pk):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=task)
    if request.method == "POST":
        form = TaskForm(data=request.POST, instance=task, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("creation_tasks"))
    return render(request, 'mainapp/edit_creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'task':task,
        'form':form
    })

@login_required
def creation_tasks_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return HttpResponseRedirect(reverse('creation_tasks'))

@user_passes_test(lambda u: u.is_superuser)
def all_users(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None

    users = CustomUser.objects.all().values_list('id', 'username', 'last_login', 'is_active', 'right__usertype_id__name')
    users.query = pickle.loads(pickle.dumps(users.query))
    
    usersdata = UserData.objects.all()
    non_active_user = CustomUser.objects.filter(is_active=False)
    
    return render(request, 'mainapp/all_users.html', context={
        'title':"Все пользователи",
        "right":right,
        'users': users,
        'userdata': usersdata,
        'non_active_user': non_active_user
    })



@user_passes_test(lambda u: u.is_superuser)
def edit_user(request, user_id):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(id=user_id)

    try:
        userdata = UserData.objects.get(user=user_id)
    except:
        userdata = UserData.objects.create(user=user, gender="M")

    try:
        right = Right.objects.get(user_id=user_id)
    except:
        right = Right.objects.create(user_id=user, usertype_id=None)

    userform = CustomUserChangeForm(instance=user)
    userdataform = UserDataForm(instance=userdata)
    rightform = RightForm(instance = right)

    if request.method =='POST':

        userform = CustomUserChangeForm(instance=user, data=request.POST)
        userdataform = UserDataForm(data=request.POST, instance=userdata)
        rightform = RightForm(data=request.POST, instance = right)

        if userform.is_valid() and userdataform.is_valid() and rightform.is_valid():
            userform.save()
            rightform.save()
            userdataform.save()
            return HttpResponseRedirect(reverse('all_users'))

    return render(request, 'mainapp/edit_user.html', context={
        'title':'Изменить пользователя',
        "right":right,
        'user':user,
        'userform':userform,
        'userdataform': userdataform,
        'rightform':rightform
    })


@user_passes_test(lambda u: u.is_superuser)
def delete_user(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    #userdata = get_object_or_404(UserData, user=user_id)
    user.delete()
    #userdata.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

TaskSystem/mainapp/templates/mainapp/includes/menu_inc.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/task.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/scrum.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/menu.css' %}">
  <link href="{% static 'colorfield/css/colorpicker.css' %}" rel="stylesheet">
  <link href="{% static 'css/colorfield.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'colorfield/css/color-picker.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
    
</head>

<body>

  <header class='header'>
    <div class='block-logo'>
      <a href='{% url "main" %}' class="logo"><img src="{% static 'images/TSlogo.png' %}" width="50" height="50"></a>
      <p class='logo-text'><a href='{% url "main" %}' class='logo-text'>TaskSystem</a></p>
    </div>
    <nav class='menu-items'>
      <ul class='menu-item'>
        
        <li><a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %} active_url {% endif %}">SCRUM</a></li>
        <li><a href="{% url 'mytasks:task_view' %}" class="{% if request.resolver_match.url_name == 'task_view' %} active_url  {% endif %}">Мои задачи</a></li>
        {% if right.usertype_id.name == "Руководитель" or right.usertype_id.name == "Администратор" %}
        <li><a href="{% url 'create' %}" class="{% if request.resolver_match.url_name == 'create' %} active_url{% endif %}">Создать задачу</a></li>
        <li><a href="{% url 'creation_tasks' %}" class="{% if request.resolver_match.url_name == 'creation_tasks' %} active_url {% endif %}">Созданные задачи</a></li>
        {% endif %}
        {% if request.user.is_superuser %}
        <li><a href="{% url 'edit_directory:directory_view' %} " class="{% if request.resolver_match.url_name == 'directory_view' %} active_url {% endif %}">Редактирование справочников</a></li>
        <li><a href="{% url 'all_users' %}" class="{% if request.resolver_match.url_name == 'all_users' %} active_url {% endif %}">Все пользователи</a></li>
        {% endif %}
        <li><a href="#" class="{% if request.resolver_match.url_name == 'account' %} active_url {% endif %}">{{ user.username }} {% if right.usertype_id.name %}[{{right.usertype_id.name}}]{% else %} [Не определен] {% endif %}</a>
        <ul>
          <li><a href="{% url 'authapp:account' %}"> Аккаунт </a></li>
          <li><a href="{% url 'auth:logout' %}" > Выйти </a></li>
        </ul>
      </li>
      </ul>
    </nav>
  </header>

TaskSystem/mainapp/templates/mainapp/includes/menu_inc_old.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/task.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/scrum.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
    

</head>
<body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'main' %}"><img src="{% static 'images/TSlogo.png' %}" width="50" height="50"> </a></li>
          <li><a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}" >Главная</a></li>
          <li><a href="{% url 'test_main' %}" class="{% if request.resolver_match.url_name == 'test_main' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}" >SCRUM </a></li>
          <li><a href="{% url 'mytasks:task_view' %}" class="{% if request.resolver_match.url_name == 'task_view' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}">Мои задачи</a></li>
          {% if right.usertype_id.name == "Руководитель" or right.usertype_id.name == "Администратор" %}
          <li><a href="{% url 'create' %}" class="{% if request.resolver_match.url_name == 'create' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}">Создать задачу</a></li>
          <li><a href="{% url 'creation_tasks' %}" class="{% if request.resolver_match.url_name == 'creation_tasks' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}">Созданные задачи</a></li>
          {% endif %}
          {% if request.user.is_superuser %}
          <li><a href="{% url 'edit_directory:directory_view' %}" class="{% if request.resolver_match.url_name == 'directory_view' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}">Редактирование справочников</a></li>
          <li><a href="{% url 'all_users' %}" class="{% if request.resolver_match.url_name == 'all_users' %} nav-link px-2 text-secondary {% else %} nav-link px-2 text-white {% endif %}">Все пользователи</a></li>
          {% endif %}
        </ul>



        <div class="dws-menu">
          
          <a href="#" class="nav-link px-2 text-white">{{ user.username }} {% if right.usertype_id.name %}[{{right.usertype_id.name}}]{% else %} [Не определен] {% endif %}</a>
          <div class='dws-menu'>
          <ul>
              <li><a href="{% url 'authapp:account' %}" class="nav-link px-2 text-white"> Аккаунт </a></li>
              <li><a href="{% url 'auth:logout' %}" class="nav-link px-2 text-white"> Выйти </a></li>
          </ul>
        </div>
        </div>
      </div>
    </div>
  </header>

TaskSystem/mainapp/templates/mainapp/includes/task_inc.html
{% load static %}

{% for task in tasks %}

<div class="task_container">
  <p>{{task.status}}</p>
  <a href={%url 'task' task.id %}><h4>Задача № {{task.id}}</h4></a>
  <p> Заказчик: {{task.author}} | Исполнитель: {% if task.executor != None %} {{task.executor}} {%else%} Не назначен {% endif %}| Статус: {{ task.status }} | Тип: {{ task.tasktype }}</p>
  <p>Заголовок: {{task.title}} </p>
  
  
  <hr>
  {%if not task.executor %}
  <a class="button" href="{% url 'mytasks:add' task.id %}">Взять задачу</a>
  {%endif%}
</div>
{% endfor %}