TaskSystem/TaskSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from authapp import views as authapp




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authapp.login, name="login"),
    path('main', mainapp.main, name ='main'),
    path('test_main', mainapp.test_main, name='test_main'),
    path('all_users', mainapp.all_users, name="all_users"),
    path('all_users/edit_user/<int:user_id>/', mainapp.edit_user, name='edit_user'),
    path('create', mainapp.create_task, name='create'),
    path("auth/", include('authapp.urls', namespace="auth")),
    path('task_<int:pk>/', mainapp.task, name='task'),
    path('tasks/', include('mytasks.urls', namespace='tasks')),
    path('creation_tasks/', mainapp.creation_tasks, name="creation_tasks"),
    path('creation_tasks/edit/<int:pk>', mainapp.edit_creation_tasks, name="edit_creation_tasks"),
    path('creation_tasks/delete/<int:pk>', mainapp.creation_tasks_delete, name='creation_tasks_delete'),
    path('edit_directory/', include('edit_directory.urls', namespace='edit_directory')),
    path('delete/<int:user_id>', mainapp.delete_user, name='delete_user'),
    path('update_task_status/', mainapp.update_task_status, name='update_task_status'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TaskSystem/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = "authapp"

urlpatterns = [

    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('account/', authapp.account, name ='account'),
    path('create_user/', authapp.create_user, name="create_user")
]

TaskSystem/authapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms import ValidationError
from .models import CustomUser, UserData

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'is_active')


class CustomUserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password', 'is_active')

        def clean_is_active(self):
            data = self.cleaned_data["is_active"]
            if data == False:
                raise ValidationError("Пользователь не активирован!")
            return data


class UserDataForm(forms.ModelForm):
    class Meta:
        model = UserData
        fields = ('name', 'lastname', 'patronymic', 'birthday', 'gender', 'number', 'email')

TaskSystem/mainapp/forms.py
from dataclasses import fields
from django import forms

from authapp.models import Right

from .models import Task, Comment


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("author", "executor", "title", "description", "files", "tasktype", "status",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "author":
                field.widget = forms.HiddenInput()



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text", "files")
                    

class RightForm(forms.ModelForm):
    class Meta:
        model = Right
        fields = ('user_id', 'usertype_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "user_id":
                field.widget = forms.HiddenInput()

TaskSystem/authapp/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from authapp.forms import CustomUserLoginForm, CustomUserCreationForm, CustomUserChangeForm, UserDataForm
from authapp.models import CustomUser, UserData, Right
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.


# def login(request):
#     form = CustomUserLoginForm()

#     if request.method == 'POST':
#         form = CustomUserLoginForm(data=request.POST)
#         if form.is_valid():
#             user = auth.authenticate(
#                 username = form.cleaned_data["username"],
#                 password = form.cleaned_data["password"],
#                 LastAuthDate = now()
#             )
        
#             if user:
#                 auth.login(request, user=user)
#                 return HttpResponseRedirect(reverse('main'))

#     return render(request, 'authapp/login.html', context={
#         'title': "Вход в систему",
#         'form': CustomUserLoginForm()
#     })

def login(request):
    form = CustomUserLoginForm()
    form_create = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserLoginForm(data=request.POST)
        form_create = CustomUserCreationForm(data=request.POST)  
       
        if form.is_valid():
            user = auth.authenticate(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password"],
                LastAuthDate = now()
            )
            test = CustomUser.objects.filter(username=user.get_username)
            messages.error(request, test)
            if user.is_active == False:    
                messages.error(request, 'Вы еще не активированы.') 
            if user.is_active == True:
                auth.login(request, user=user)
                return HttpResponseRedirect(reverse('main'))
        else:
            messages.error(request, 'Ваш аккаунт еще не активирован или вы указали неверные данные!')    

          
        if form_create.is_valid():
            form_create.save()
            messages.success(request, 'Ваша заявка на регистрацию была отправлена, пожалуйста дождитесь пока её одобрят!')
            return HttpResponseRedirect(reverse('login'))

            
    
    return render(request, 'authapp/login.html', context={
        'title': "Вход в систему",
        'form': CustomUserLoginForm(),
        'form_create': CustomUserCreationForm(),
        
    })


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('login'))


def register(request):
    form = CustomUserCreationForm()
    if request.method =='POST':
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login'))

    return render(request, 'authapp/register.html', context={
        'title': 'Регистрация аккаунта',
        'form': form
    })


@login_required
def account(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None

    try:
        userdata = UserData.objects.get(user=request.user)
    except:
        userdata = UserData.objects.create(user=request.user, gender="M")

    userform = CustomUserChangeForm(instance = request.user)
    userdataform = UserDataForm(instance = userdata)

    if request.method =="POST":
        userform = CustomUserChangeForm(instance=request.user, data=request.POST)
        userdataform = UserDataForm(instance=userdata, data=request.POST)

        if userform.is_valid() and userdataform.is_valid():
            userform.save()
            userdataform.save()
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'authapp/account.html', context={
        'title': "Мой аккаунт",
        "right":right,
        'userform': userform,
        'userdataform':userdataform
    })

@user_passes_test(lambda u: u.is_superuser)
def create_user(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    userform = CustomUserCreationForm()
    if request.method == 'POST':
        userform = CustomUserCreationForm(data=request.POST)

        if userform.is_valid():
            userform.save()
            return HttpResponseRedirect(reverse('all_users'))

    return render(request, 'authapp/create_user.html', context={
        'title': 'Создание аккаунта',
        "right":right,
        'userform': userform
    })

TaskSystem/mainapp/views.py
from cmath import pi
from turtle import right
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from .models import Task, Comment
from edit_directory.models import Status
from .forms import RightForm, TaskForm, CommentForm
from authapp.models import CustomUser, UserData, Right
from authapp.forms import CustomUserChangeForm, UserDataForm
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import pickle
# Create your views here.


@login_required
def main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@login_required
def test_main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/test_main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@csrf_exempt
def update_task_status(request):
    if request.method == 'POST':
        # Получаем данные из POST-запроса
        task_id = request.POST.get('task_id')
        status_id = request.POST.get('status_id')
        # Изменяем статус задачи
        task = Task.objects.get(id=task_id)
        status = Status.objects.get(id=status_id)
        task.status = status
        task.save()
        # Возвращаем успешный ответ в формате JSON
        return JsonResponse({'success': True})
    # В случае неправильного метода запроса возвращаем ошибку
    return JsonResponse({'success': False, 'message': 'Метод запроса должен быть POST'})


@login_required
def task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    comment = Comment.objects.filter(task=task)
    form = CommentForm()
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    if request.method =="POST":
        form = CommentForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.data = now
            form.author = request.user
            form.task = task
            form.save()
            return HttpResponseRedirect(reverse('task', args=[pk]))
    return render(request, 'mainapp/task.html', context={
        "title": f"Задача №{task.id}",
        'task':task,
        'comments':comment,
        'form':form,
        "right":right
    })

@login_required
def create_task(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(pk=request.user.pk)
    form = TaskForm()
    # form.author = user
    if request.method == "POST":
        form = TaskForm(data=request.POST)
        
        if form.is_valid():
            form = form.save(commit=False)
            form.author = user
            form.save()
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'mainapp/create.html', context={
        'title':"Создать задачу",
        'form': form,
        "right":right,
    })

@login_required
def creation_tasks(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=Task.objects.filter(author=request.user)
    return render(request, 'mainapp/creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'tasks':task
    })

@login_required
def edit_creation_tasks(request, pk):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=task)
    if request.method == "POST":
        form = TaskForm(data=request.POST, instance=task, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("creation_tasks"))
    return render(request, 'mainapp/edit_creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'task':task,
        'form':form
    })

@login_required
def creation_tasks_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return HttpResponseRedirect(reverse('creation_tasks'))

@user_passes_test(lambda u: u.is_superuser)
def all_users(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None

    users = CustomUser.objects.all().values_list('id', 'username', 'last_login', 'is_active', 'right__usertype_id__name')
    users.query = pickle.loads(pickle.dumps(users.query))
    
    usersdata = UserData.objects.all()
    non_active_user = CustomUser.objects.filter(is_active=False)
    
    return render(request, 'mainapp/all_users.html', context={
        'title':"Все пользователи",
        "right":right,
        'users': users,
        'userdata': usersdata,
        'non_active_user': non_active_user
    })



@user_passes_test(lambda u: u.is_superuser)
def edit_user(request, user_id):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(id=user_id)

    try:
        userdata = UserData.objects.get(user=user_id)
    except:
        userdata = UserData.objects.create(user=user, gender="M")

    try:
        right = Right.objects.get(user_id=user_id)
    except:
        right = Right.objects.create(user_id=user, usertype_id=None)

    userform = CustomUserChangeForm(instance=user)
    userdataform = UserDataForm(instance=userdata)
    rightform = RightForm(instance = right)

    if request.method =='POST':

        userform = CustomUserChangeForm(instance=user, data=request.POST)
        userdataform = UserDataForm(data=request.POST, instance=userdata)
        rightform = RightForm(data=request.POST, instance = right)

        if userform.is_valid() and userdataform.is_valid() and rightform.is_valid():
            userform.save()
            rightform.save()
            userdataform.save()
            return HttpResponseRedirect(reverse('all_users'))

    return render(request, 'mainapp/edit_user.html', context={
        'title':'Изменить пользователя',
        "right":right,
        'user':user,
        'userform':userform,
        'userdataform': userdataform,
        'rightform':rightform
    })


@user_passes_test(lambda u: u.is_superuser)
def delete_user(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    #userdata = get_object_or_404(UserData, user=user_id)
    user.delete()
    #userdata.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

TaskSystem/mainapp/templates/authapp/account.html
{% load static %}
{% include 'mainapp/includes/menu_inc.html' %}

<div class="main_page">
    
<h3>Мой аккаунт</h3>
<form method="post">
    {% csrf_token %}</p>
    {{ userform.as_p }}

    <h4>Профиль</h4>
    {{userdataform.as_p}}
    <input type="submit" value="Изменить профиль">
</form>

</div>

TaskSystem/mainapp/templates/authapp/create_user.html
{% load static %}

{% include 'mainapp/includes/menu_inc.html' %}

<div class='page_style_account'>
<form method="post">
  {% csrf_token %}
  <h3>Создание пользователя</h3>
  {{userform.as_p}}
  <input type="submit" value="Создать пользователя">
</form>
</div>

TaskSystem/mainapp/templates/authapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    {% comment %}  {% endcomment %}
    {% comment %} <script src={% static 'js/login_script.js' %} defer></script> {% endcomment %}
    {% comment %} <script type="text/javascript" src={% static "js/login_script.js" %}></script> {% endcomment %}
    
</head>
<body>
    <img class='main_logo' src="{% static 'images/TSlogo.png' %}">
    <article class='container'>
        <div class='block'>
        <section class ="block__item block-item">
            <h2 class="block-item__title">У вас уже есть аккаунт?</h2>
            <button class="block-item__btn signin-btn">Войти</button>
        </section>
        <section class ="block__item block-item">
            <h2 class="block-item__title">У вас нет аккаунта?</h2>
            <button class="block-item__btn signup-btn">Зарегестрироваться</button>
        </section>
    </div>
    
<div class="form-box">

    <form class="form form_signin" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        
        {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<h3 class="form__title">Вход</h3>
        <p>
            <input class="form__input" type="text" name="username" placeholder="Логин">
        </p>

        <p>
            <input class="form__input" type="password" name="password" placeholder="Пароль">
        </p>
        {% comment %} <p class="user-activate">{% if request.user.is_active == False %} Пользователь не активирован! {% endif %} </p> {% endcomment %}       
        <p>
            <input class="form__btn" type="submit" value="Войти"/>
        </p>
        <p>
            <a href='#' class="form_forgot">Восстановить пароль</a>
        </p>

    </form>


    <form class="form form_signup" action="{% url 'login' %}" method="post" >
        {% csrf_token %}
        {% comment %} <p>{{form_create.username}}</p>
        <p>{{form_create.password}}</p>
        <p>{{form_create.password2}}</p> {% endcomment %}
        <h3 class="form__title">Регистрация</h3>
        <p>
            <input class="form__input" type="text" name="username" placeholder="Логин">
        </p>       
        <p>
            <input class="form__input" type="password" name="password1" placeholder="Пароль">
        </p>
        <p>
            <input class="form__input" type="password" name="password2" placeholder="Повторите пароль">
        </p>
        
        <p>
            <input class="form__btn form__btn_signup" type="submit" value="Зарегестрироваться"/>
        </p>
        {% if form_create.errors %}
        <ul>
            {% for field in form_create %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}
    </form>

</div>

    </article>

    <script type="text/javascript" src="{% static 'js/login_script.js' %}"></script>  
</body>
</html>

TaskSystem/mainapp/templates/authapp/login_old.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Вход в систему
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" action="{% url 'login' %}" method="post">
					{% csrf_token %}

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					
					<p class="user-activate">{% if request.user.is_active == False %} Пользователь не активирован! {% endif %} </p>

					
					<a href="{% url 'auth:register' %}">Нет аккаунта? Зарегестрироваться</a>
					<div class="container-login100-form-btn m-t-32">
						<input class="login100-form-btn" type="submit" value="Войти"/>

					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

TaskSystem/mainapp/templates/authapp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Вход в систему
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" action="{% url 'auth:register' %}" method="post">
					{% csrf_token %}


					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name=username placeholder="Пользователь">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password1" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Reset password">
						<input class="input100" type="password" name="password2" placeholder="Reset Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>
					<div class="container-login100-form-btn m-t-32">
						<input class="login100-form-btn" type="submit" value="Зарегестрироваться"/>

					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>