TaskSystem/TaskSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from authapp import views as authapp




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authapp.login, name="login"),
    path('main', mainapp.main, name ='main'),
    path('test_main', mainapp.test_main, name='test_main'),
    path('all_users', mainapp.all_users, name="all_users"),
    path('all_users/edit_user/<int:user_id>/', mainapp.edit_user, name='edit_user'),
    path('create', mainapp.create_task, name='create'),
    path("auth/", include('authapp.urls', namespace="auth")),
    path('task_<int:pk>/', mainapp.task, name='task'),
    path('tasks/', include('mytasks.urls', namespace='tasks')),
    path('creation_tasks/', mainapp.creation_tasks, name="creation_tasks"),
    path('creation_tasks/edit/<int:pk>', mainapp.edit_creation_tasks, name="edit_creation_tasks"),
    path('creation_tasks/delete/<int:pk>', mainapp.creation_tasks_delete, name='creation_tasks_delete'),
    path('edit_directory/', include('edit_directory.urls', namespace='edit_directory')),
    path('delete/<int:user_id>', mainapp.delete_user, name='delete_user'),
    path('update_task_status/', mainapp.update_task_status, name='update_task_status'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TaskSystem/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = "authapp"

urlpatterns = [

    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('account/', authapp.account, name ='account'),
    path('create_user/', authapp.create_user, name="create_user")
]

TaskSystem/mainapp/models.py
from django.db import models
from authapp.models import CustomUser
from django.utils import timezone
from django.contrib.auth import get_user_model
from edit_directory.models import TaskType, Status

class Task(models.Model):

    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", default=get_user_model(), related_name='authors', blank=True)
    executor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Исполнитель", default=None, related_name='executors', blank=True, null=True)
    title = models.CharField("Заголовок", max_length=100, default=None)
    description = models.TextField("Описание", max_length=250, default="")
    files = models.FileField(upload_to="files/", verbose_name="Файлы", blank=True, default=None)
    tasktype = models.ForeignKey(TaskType, on_delete=models.DO_NOTHING, verbose_name="Тип заявки", default=None)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING, verbose_name="Статус", default="В ожидании")
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.description


class HistoryTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.DO_NOTHING, verbose_name="Задача", default=None, related_name='task')
    #Придумать реализацию сохранения старой инфы
    #Отображение новой инфы
    change = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, verbose_name="Задача", default=None, related_name='сomments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="Автор", default=None)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name="Текст", max_length=100, blank=True)
    files = models.FileField(upload_to="comment_files/", verbose_name="Прикрепленные файлы", blank=True, default=None)

    def __str__(self):
        return f"{self.author}: {self.text}"

TaskSystem/mainapp/forms.py
from dataclasses import fields
from django import forms

from authapp.models import Right

from .models import Task, Comment


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("author", "executor", "title", "description", "files", "tasktype", "status",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "author":
                field.widget = forms.HiddenInput()



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text", "files")
                    

class RightForm(forms.ModelForm):
    class Meta:
        model = Right
        fields = ('user_id', 'usertype_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == "user_id":
                field.widget = forms.HiddenInput()

TaskSystem/mainapp/views.py
from cmath import pi
from turtle import right
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from .models import Task, Comment
from edit_directory.models import Status
from .forms import RightForm, TaskForm, CommentForm
from authapp.models import CustomUser, UserData, Right
from authapp.forms import CustomUserChangeForm, UserDataForm
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import pickle
# Create your views here.


@login_required
def main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@login_required
def test_main(request):
    CustomUser.objects.filter(pk=request.user.pk).update(LastAuthDate=now())
    tasks = Task.objects.all()
    statuses = Status.objects.all()
    todo = Task.objects.filter(status=1)
    in_progress = Task.objects.filter(status=2)
    done = Task.objects.filter(status=3)
    rework = Task.objects.filter(status=4)
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    return render(request, 'mainapp/test_main.html', context={
        "title": "Главное меню",
        "tasks": tasks,
        "right":right,
        "todo": todo,
        "in_progress": in_progress,
        "done": done, 
        "rework":rework,
        "statuses": statuses
    })

@csrf_exempt
def update_task_status(request):
    if request.method == 'POST':
        # Получаем данные из POST-запроса
        task_id = request.POST.get('task_id')
        status_id = request.POST.get('status_id')
        # Изменяем статус задачи
        task = Task.objects.get(id=task_id)
        status = Status.objects.get(id=status_id)
        task.status = status
        task.save()
        # Возвращаем успешный ответ в формате JSON
        return JsonResponse({'success': True})
    # В случае неправильного метода запроса возвращаем ошибку
    return JsonResponse({'success': False, 'message': 'Метод запроса должен быть POST'})


@login_required
def task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    comment = Comment.objects.filter(task=task)
    form = CommentForm()
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    if request.method =="POST":
        form = CommentForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.data = now
            form.author = request.user
            form.task = task
            form.save()
            return HttpResponseRedirect(reverse('task', args=[pk]))
    return render(request, 'mainapp/task.html', context={
        "title": f"Задача №{task.id}",
        'task':task,
        'comments':comment,
        'form':form,
        "right":right
    })

@login_required
def create_task(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(pk=request.user.pk)
    form = TaskForm()
    # form.author = user
    if request.method == "POST":
        form = TaskForm(data=request.POST)
        
        if form.is_valid():
            form = form.save(commit=False)
            form.author = user
            form.save()
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'mainapp/create.html', context={
        'title':"Создать задачу",
        'form': form,
        "right":right,
    })

@login_required
def creation_tasks(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=Task.objects.filter(author=request.user)
    return render(request, 'mainapp/creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'tasks':task
    })

@login_required
def edit_creation_tasks(request, pk):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    task=get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=task)
    if request.method == "POST":
        form = TaskForm(data=request.POST, instance=task, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("creation_tasks"))
    return render(request, 'mainapp/edit_creation_tasks.html', context={
        'title':"Созданные задачи",
        "right":right,
        'task':task,
        'form':form
    })

@login_required
def creation_tasks_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return HttpResponseRedirect(reverse('creation_tasks'))

@user_passes_test(lambda u: u.is_superuser)
def all_users(request):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None

    users = CustomUser.objects.all().values_list('id', 'username', 'last_login', 'is_active', 'right__usertype_id__name')
    users.query = pickle.loads(pickle.dumps(users.query))
    
    usersdata = UserData.objects.all()
    non_active_user = CustomUser.objects.filter(is_active=False)
    
    return render(request, 'mainapp/all_users.html', context={
        'title':"Все пользователи",
        "right":right,
        'users': users,
        'userdata': usersdata,
        'non_active_user': non_active_user
    })



@user_passes_test(lambda u: u.is_superuser)
def edit_user(request, user_id):
    try:
        right = Right.objects.get(user_id=request.user)
    except:
        right = None
    user = CustomUser.objects.get(id=user_id)

    try:
        userdata = UserData.objects.get(user=user_id)
    except:
        userdata = UserData.objects.create(user=user, gender="M")

    try:
        right = Right.objects.get(user_id=user_id)
    except:
        right = Right.objects.create(user_id=user, usertype_id=None)

    userform = CustomUserChangeForm(instance=user)
    userdataform = UserDataForm(instance=userdata)
    rightform = RightForm(instance = right)

    if request.method =='POST':

        userform = CustomUserChangeForm(instance=user, data=request.POST)
        userdataform = UserDataForm(data=request.POST, instance=userdata)
        rightform = RightForm(data=request.POST, instance = right)

        if userform.is_valid() and userdataform.is_valid() and rightform.is_valid():
            userform.save()
            rightform.save()
            userdataform.save()
            return HttpResponseRedirect(reverse('all_users'))

    return render(request, 'mainapp/edit_user.html', context={
        'title':'Изменить пользователя',
        "right":right,
        'user':user,
        'userform':userform,
        'userdataform': userdataform,
        'rightform':rightform
    })


@user_passes_test(lambda u: u.is_superuser)
def delete_user(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    #userdata = get_object_or_404(UserData, user=user_id)
    user.delete()
    #userdata.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

TaskSystem/mainapp/templates/mainapp/all_users.html
{% load static %}
{% include 'mainapp/includes/menu_inc.html' %}


<div class='page_style'>
<h3>Все пользователи</h3>
<hr>
<a class="button" href ="{% url 'auth:create_user' %}" >Создать пользователя </a>
<hr>


<table class="primary">
    <thead>
      <tr>
        <th>Username</th>
        <th>Последний вход</th>
        <th>Активность<th>       
        <th>Тип пользователя</th> 
        <th><th>
        <th><th>
      </tr>
    </thead>
    <tbody>
        {% for user in users %}
      <tr>
        <td>{{user.username}}</td>
        <td>{{user.last_login}}</td>
        <td>{{user.is_active}}</td>
        <td></td>
        <td>{% if user.right__usertype_id__name %}{{user.right__usertype_id__name}} {% else %} Не определен {%endif%}</td>
        
        <td><a href ="{% url 'edit_user' user.id %}">Изменить  </a></td>
        <td><a href ="{% url 'delete_user' user.id %}">Удалить </a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


<h3>Требуют активации</h3>
<table class="primary">
    <thead>
      <tr>
        <th>Username</th>
        <th>Последний вход</th>
        <th>Активность<th>        
        <th><th>
        <th><th>
      </tr>
    </thead>
    <tbody>
        {% for user in non_active_user %}
      <tr>
        <td>{{user.username}}</td>
        <td>{{user.last_login}}</td>
        <td>{{user.is_active}}</td>
        <td>{{user.type}}</td>
        <td><a href ="{% url 'edit_user' user.id %}">Изменить  </a></td>
        <td><a href ="{% url 'delete_user' user.id %}">Удалить </a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

TaskSystem/mainapp/templates/mainapp/create.html
{% load static %}

{% include 'mainapp/includes/menu_inc.html'%}
<div class="main_page">
<br>
<h3>Создать задачу:</h3>


<form class="pure-form" action="{% url 'create' %}" method="post">
    {% csrf_token %}
    <p>{{error}}</p>
    {{ form.as_p }}

<br>
    <input class="pure-button pure-button-primary" type="submit" value="Создать задачу">
</form>
</div>

</body>
</html>

TaskSystem/mainapp/templates/mainapp/creation_tasks.html
{% load static %}
{% include 'mainapp/includes/menu_inc.html' %}
  <div class='page_style'>
    <h3>Созданные задачи:</h3>

    {% for task in tasks %}

    <div class="task_container" style="--status-color: {{task.status.color_status}};">
        
      <a href={%url 'task' task.id %}><h4>Задача № {{task.id}}</h4></a>
      <p> Заказчик: {{task.author}} | Исполнитель: {% if task.executor == None %} Не назначен {% else %} {{task.executor}} {%endif%}  | Статус: {{ task.status }} | Тип: {{ task.tasktype }}</p>
      <p>Описание: </p>
      <p>{{task.title}}</p>
      <p>{{task.files}}</p>
      <a class ='button' href="{% url 'edit_creation_tasks' task.pk %}">Редактирование</a>
      <a class ='button' href="{% url 'creation_tasks_delete' task.pk %}">Снять задачу</a>
    </div>
    {% endfor %}
  </div>
</body>

</html>

TaskSystem/mainapp/templates/mainapp/edit_creation_tasks.html
{% load static %}

{% include 'mainapp/includes/menu_inc.html'%}
<div class="main_page">
<br>
<h3>Изменение задачи №{{task.id}}:</h3>


<form action="{% url 'edit_creation_tasks' task.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

<br>
    <input class="button" type="submit" value="Сохранить изменения">
</form>
</div>

</body>
</html>

TaskSystem/mainapp/templates/mainapp/edit_user.html
{% load static %}
{% include 'mainapp/includes/menu_inc.html' %}

<div class='page_style'>
<h2>Пользователь</h2>
<form method="post" class="third maindiv">
    {% csrf_token %}
    <span>{{userform.username}}</span>
    
    <label>
        <input type="checkbox" {% if user.is_active == True%} checked {% endif%} name={{userform.is_active.name}} >
        <span class="checkable" >Пользователь активирован</span>
      </label>
    
    {{rightform.as_p}}

<h2>Профиль</h2>
    {{userdataform.as_p}}
    <input type="submit" value="Сохранить изменения">
    </div>
</form>

TaskSystem/mainapp/templates/mainapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %});">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Вход в систему
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5">

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<a class="login100-form-btn" href = "{% url 'main' %}"/>
							Login
						</a>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

TaskSystem/mainapp/templates/mainapp/main.html
{% load static %}

{% include 'mainapp/includes/menu_inc.html'%}
<br>
<div class='page_style'>
    {% block content %}
    <div class="scrum-board" >
    {% for status in statuses %}
      <div class="scrum-column" data-status="{{status.id}}" >
        <h2>{{status}}</h2>
        <ul class="scrum-list" id="task_list" droppable="true">
          {% if not status.children.exists %}
            <li class="empty-placeholder">+</li>
        {% endif %}

          {% for item in tasks %} 
          {%if item.status == status%}

         
          <li class='task_item task_list' draggable="true" data-task-id="{{item.id}}" style="--status-color: {{status.color_status}};"> {{item.tasktype}}
            <p><a href={%url 'task' item.id %}> Задача № {{item.id}}</a> {{ item.title }}</p>
            <p>Автор: {{item.author}}</p>
            <p>Исполнитель: {% if item.executor == None %} Не назначен {% else %} {{item.executor}} {%endif%}</p>
          </li>
          {% comment %} {%else%}
          <li class="empty-placeholder"></li> {% endcomment %}
          {%endif%}
          {% endfor %}
        </ul>
      </div>
      {%endfor%}
      {%endblock%}
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scrum.js' %}"></script>  
</body>
</html>

TaskSystem/mainapp/templates/mainapp/task.html
{% include 'mainapp/includes/menu_inc.html' %}
{% load static %}



<div class="task_container_check" style="--status-color: {{task.status.color_status}};">
<h3> Задача № {{task.id}}</h3>
  <p> Заказчик: {{task.author}} | Исполнитель: {{task.executor}} | Статус: {{ task.status }} | Тип: {{ task.tasktype }}</p>
  <p>{{task.title}}</p>
  <hr>
  <p>Описание: </p>
  <p>{{task.description}}</p>
  {% if task.files%}
  <p><a href='{{ settings.MEDIA_URL }}{{task.files.url}}' download><img style="width: 50px" src ="{%static 'images/icons/doc-icon.png'%}"> {{task.files.name}} </a></p>
  {%endif%}
<hr><h4>Оставить комментарий</h4>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}

<br>
  <input class="button" type="submit" value="Отправить">
</form>
<br>
<h3>Комментарии</h3>

{% for comment in comments %}

<div class="card">
  <p>{{comment}}</p>
  {%if comment.files%}
  <p><a href='{{ settings.MEDIA_URL }}{{comment.files.url}}' download> <img style="width: 30px" src ="{%static 'images/icons/doc-icon.png'%}"> {{comment.files.name}}</a></p>
  {%endif%}
</div>
  <hr>
  {% endfor %}

</div>
</body>
</html>

TaskSystem/mainapp/templates/mainapp/test_main.html
{% load static %}

{% include 'mainapp/includes/menu_inc.html'%}
<br>
<div class='page_style'>
    {% block content %}
    <div class="scrum-board" droppable='true'>
      <div class="scrum-column" droppable='true'>
        <h2>В ожидании</h2>
        <ul class="scrum-list" id="todo-list" >
          {% for item in todo %}
          <li class='task_item todo-list' draggable="true"> {{item.tasktype}}
            <p><a href={%url 'task' item.id %}> Задача № {{item.id}}</a> {{ item.title }}</p>
            <p>Автор: {{item.author}}</p>
            <p>Исполнитель: {{item.executor}}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="scrum-column" droppable='true' >
        <h2>В работе</h2>
        <ul class="scrum-list" id="in-progress-list">
          {% for item in in_progress %}
          <li class='task_item in-progress-list' draggable="true">{{item.tasktype}}
            <p><a href={%url 'task' item.id %}> Задача № {{item.id}}</a> {{ item.title }}</p>
            <p>Автор: {{item.author}}</p>
            <p>Исполнитель: {{item.executor}}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="scrum-column" droppable='true' >
        <h2>Выполнены</h2>
        <ul class="scrum-list " id="done-list" >
          {% for item in done %}
          <li class='task_item done_list' draggable="true">{{item.tasktype}}
            <p><a href={%url 'task' item.id %}> Задача № {{item.id}}</a> {{ item.title }}</p>
            <p>Автор: {{item.author}}</p>
            <p>Исполнитель: {{item.executor}}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="scrum-column" droppable='true'>
        <h2>Доработка</h2>
        <ul class="scrum-list" id="rework-list" >
          {% for item in rework %}
          <li class='task_item rework-list' draggable="true">{{item.tasktype}}
            <p><a href={%url 'task' item.id %}> Задача № {{item.id}}</a> {{ item.title }}</p>
            <p>Автор: {{item.author}}</p>
            <p>Исполнитель: {{item.executor}}</p>
          </li>
            
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endblock %}

</div>
<script type="text/javascript" src="{% static 'js/scrum.js' %}"></script>  
</body>
</html>